const projects = {
  spam: { label: '01 / MACHINE LEARNING & DEPLOYMENT', title: 'Spam Detection Service', body: '<p>I took a trained text classification model and built a service around it, covering the path from incoming message to cloud deployment.</p><h3>How it works</h3><p>NLTK preprocesses and tokenises the message. CountVectorizer transforms the processed text into numerical features, which a Multinomial Naive Bayes classifier uses to predict spam or legitimate text.</p><h3>The engineering work</h3><ul><li>FastAPI prediction and health endpoints.</li><li>Automated checks with Ruff and pytest.</li><li>Docker packaging and image versioning through GHCR.</li><li>GitHub Actions deployment to an Azure VM, with a health check after deployment.</li></ul><h3>What I learned</h3><p>Connecting model inference to a repeatable deployment process means paying attention to dependencies, runtime behaviour, and how the service is verified after release.</p><div class="dialog-actions"><a class="button" href="https://github.com/MohOdejimi/spam-detection-api" target="_blank" rel="noopener noreferrer">Explore the repository</a></div>' },
  vault: { label: '02 / AI APPLICATION · IN PROGRESS', title: 'ContextVault', body: '<p>I’m building a knowledge base for organisations to upload documents and ask questions with answers supported by sources.</p><h3>Current focus</h3><p>The FastAPI backend foundation: user registration and authentication, PostgreSQL persistence, SQLAlchemy models, Alembic migrations, and automated testing.</p><h3>Planned document workflow</h3><p>Upload PDF, DOCX, Markdown, and text documents; parse and chunk their contents; create embeddings; retrieve relevant passages; and generate answers with source references.</p><h3>Planned user experience</h3><p>A Next.js frontend for uploading documents and asking questions, backed by FastAPI, PostgreSQL, and an LLM.</p><h3>Why I’m building it</h3><p>To learn how the components of a useful AI product fit together, including data access, document processing, retrieval quality, and clear evidence for an answer.</p><p>The document ingestion and question-answering features are still planned, rather than presented as completed functionality.</p>' },
  chat: { label: '03 / COLLABORATIVE BACKEND ENGINEERING', title: 'ChatMonie', body: '<p>ChatMonie was built by a team of three for the BMoni hackathon and won third place.</p><h3>My contribution</h3><p>I worked alongside another backend engineer while our third teammate built the frontend. My work covered onboarding, KYC, and smart wallet verification.</p><h3>Working as a team</h3><p>The project gave me experience delivering backend workflows as part of a shared product, coordinating with teammates, and connecting the frontend experience to server-side functionality.</p><h3>Project credit</h3><p>This was a team achievement. The product and its implementation reflect the combined work of all three contributors.</p><div class="dialog-actions"><a class="button" href="https://chatmonie.vercel.app" target="_blank" rel="noopener noreferrer">Visit ChatMonie</a></div>' }
};
const dialog = document.querySelector('#project-dialog');
document.querySelectorAll('[data-project]').forEach(button => button.addEventListener('click', () => {
  const project = projects[button.dataset.project];
  document.querySelector('#dialog-label').textContent = project.label;
  document.querySelector('#dialog-title').textContent = project.title;
  document.querySelector('#dialog-body').innerHTML = project.body;
  dialog.showModal();
}));
document.querySelector('.dialog-close').addEventListener('click', () => dialog.close());
dialog.addEventListener('click', event => { if (event.target === dialog) { const bounds = dialog.getBoundingClientRect(); if (event.clientX < bounds.left || event.clientX > bounds.right || event.clientY < bounds.top || event.clientY > bounds.bottom) dialog.close(); }});
document.querySelector('#year').textContent = new Date().getFullYear();
